--Part 1 (list the columns and their data types in the table as a SQL comment.)
    --id: int
    --employer: varchar(255)
    --name: varchar(255)
    --skills: varchar(255)
--Part 2
    --SELECT name FROM employer WHERE location = "St. Louis City"
--Part 3
    --DROP TABLE job
--Part 4
